{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE UnicodeSyntax     #-}

-- https://stackoverflow.com/questions/58777439/haskell-data-yaml-utf-8-decoding

module MInfo.T.TestData where

import Data.ByteString  ( ByteString, intercalate )
  
--------------------------------------------------------------------------------

info1T ∷ ByteString
info1T =
  intercalate "\n"
    [ "artist: Depeche Mode"
    , "source: World We Live in and Live in Hamburg,The"
    , "live_type: Live"
    , "live_location: Hamburg"
    , "live_date: 1984-12-14"
    , "tracks:"
    , " - title: Something to Do"
    , " - title: Two Minute Warning"
    , "" -- force a terminating newline
    ]

info2T ∷ ByteString
info2T =
  intercalate "\n"
    [ "artist: Depeche Mode"
    , "source: Devotional"
    , "catno: DMDVD4"
    , "tracks:"
    , "  -"
    , "    - title: Higher Love"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: World in my Eyes"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Walking in my Shoes"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Behind the Wheel"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Stripped"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Condemnation"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Judas"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Mercy in You"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: I Feel You"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Never Let Me Down Again"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Rush"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: In your Room"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Personal Jesus"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Enjoy the Silence"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Fly on the Windscreen"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Everything Counts"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Credits - Death's Door "
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Halo"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "    - title: Policy of Truth"
    , "      live_type: Live"
    , "      live_location: Stade Couvert R\195\169gional, Li\195\169vin, France"
    , "      live_date: 1993-07-29"
    , "" -- force a terminating newline
    ]

info3T ∷ ByteString
info3T =
  intercalate "\n"
    [ "---"
    , "artist: Depeche Mode"
    , "catno: 12345"
    , "live_date: 1993-07-31"
    , "live_location: Crystal Palace"
    , "live_type: Live"
    , "release: 1993"
    , "source: Radio 1 in Concert"
    , "tracks:"
    , "  - title: Walking in my Shoes"
    , "  - title: Halo"
    , "  - title: Stripped"
    , "  - title: Condemnation"
    , "  - title: Judas"
    , "  - title: I Feel You"
    , "  - title: Never Let Me Down Again"
    , "  - title: Rush"
    , "  - title: In your Room"
    , "  - title: Personal Jesus"
    , "  - title: Enjoy the Silence"
    , "  - title: Everything Counts"
    , "" -- force a terminating newline
    ]

info4T ∷ ByteString
info4T =
  intercalate "\n"
    [ "---"
    , "artist: Depeche Mode"
    , "catno: BX Stumm 300"
    , "release: 2009-04-17"
    , "source: Sounds of the Universe  (Deluxe Box Set)"
    , "tracks:"
    , "  -"
    , "    - title: In Chains"
    , "    - title: Hole to Feed"
    , "    - title: Wrong"
    , "    - title: Fragile Tension"
    , "    - title: Little Soul"
    , "    - title: In Sympathy"
    , "    - title: Peace"
    , "    - title: Come Back"
    , "    - title: Spacewalker"
    , "    - title: Perfect"
    , "    - title: 'Miles Away - the Truth is'"
    , "    - title: Jezebel"
    , "    - title: Corrupt"
    , "    - title: 'Interlude #5'"
    , "  -"
    , "    - title: Light"
    , "    - title: 'Sun and the Moon and the Stars,The'"
    , "    - title: Ghost"
    , "    - title: Esque"
    , "    - title: Oh Well"
    , "    - title: Corrupt"
    , "      version: Efdemin Remix"
    , "    - title: In Chains"
    , "      version: Minilogue's Earth Remix"
    , "    - title: Little Soul"
    , "      version: Thomas Fehlmann Flowing Ambient Mix"
    , "    - title: Jezebel"
    , "      version: SixToes Remix"
    , "    - title: Perfect"
    , "      version: Drone Mix"
    , "    - title: Wrong"
    , "      version: Caspa Remix"
    , "  -"
    , "    - title: 'Little 15'"
    , "      live_type: Demo"
    , "    - title: 'Clean'"
    , "      live_type: Demo"
    , "    - title: 'Sweetest Perfection'"
    , "      live_type: Demo"
    , "    - title: 'Walking in my Shoes'"
    , "      live_type: Demo"
    , "    - title: 'I Feel You'"
    , "      live_type: Demo"
    , "    - title: 'Judas'"
    , "      live_type: Demo"
    , "    - title: 'Surrender'"
    , "      live_type: Demo"
    , "    - title: 'Only When I Lose Myself'"
    , "      live_type: Demo"
    , "    - title: \"Nothing's Impossible\""
    , "      live_type: Demo"
    , "    - title: 'Corrupt'"
    , "      live_type: Demo"
    , "    - title: 'Peace'"
    , "      live_type: Demo"
    , "    - title: 'Jezebel'"
    , "      live_type: Demo"
    , "    - title: 'Come Back'"
    , "      live_type: Demo"
    , "    - title: 'In Chains'"
    , "      live_type: Demo"
    , "" -- force a terminating newline
    ]

info5T ∷ ByteString
info5T =
  intercalate "\n"
    [ "---"
    , "artist: Depeche Mode"
    , "release: 2009-04-17"
    , "source: Sounds of the Universe  (Deluxe Box Set)"
    , "tracks:"
    , "  -"
    , "    - title: 'In Chains'"
    , "    - title: 'Hole to Feed'"
    , "    - title: 'Wrong'"
    , "    - title: 'Fragile Tension'"
    , "    - title: 'Little Soul'"
    , "    - title: 'In Sympathy'"
    , "    - title: 'Peace'"
    , "    - title: 'Come Back'"
    , "    - title: 'Spacewalker'"
    , "    - title: 'Perfect'"
    , "    - title: 'Miles Away / The Truth Is'"
    , "    - title: 'Jezebel'"
    , "    - title: 'Corrupt'"
    , "    - title: 'Interlude #5'"
    , "    - title: 'Light'"
    , "    - title: 'Sun and the Moon and the Stars,The'"
    , "    - title: 'Ghost'"
    , "    - title: 'Esque'"
    , "    - title: 'Oh Well'"
    , "  -"
    , "    - title: 'Little 15'"
    , "      version: Demo"
    , "    - title: 'Clean'"
    , "      version: Demo"
    , "    - title: 'Sweetest Perfection'"
    , "      version: Demo"
    , "    - title: 'Walking in my Shoes'"
    , "      version: Demo"
    , "    - title: 'I Feel You'"
    , "      version: Demo"
    , "    - title: 'Judas'"
    , "      version: Demo"
    , "    - title: 'Surrender'"
    , "      version: Demo"
    , "    - title: 'Only When I Lose Myself'"
    , "      version: Demo"
    , "    - title: \"Nothing's Impossible\""
    , "      version: Demo"
    , "    - title: 'Corrupt'"
    , "      version: Demo"
    , "    - title: 'Peace'"
    , "      version: Demo"
    , "    - title: 'Jezebel'"
    , "      version: Demo"
    , "    - title: 'Come Back'"
    , "      version: Demo"
    , "    - title: 'In Chains'"
    , "      version: Demo"
    , "  -"
    , "    - title: Oh Well"
    , "      version: Single Edit"
    , "    - title: 'Wrong'"
    , "      version: Studio Session Mix"
    , "    - title: 'Come Back'"
    , "      version: Studio Session Mix"
    , "    - title: 'Corrupt'"
    , "      version: Studio Session Mix"
    , "    - title: 'Miles Away / The Truth is'"
    , "      version: Lagos Boys Choir Remix"
    , "    - title: 'Sun and the Moon and the Stars,The'"
    , "      version: \"Electronic Periodic's Microdrum Mix\""
    , "    - title: 'Ghost'"
    , "      version: Le Weekend Remix"
    , "    - title: 'In Chains'"
    , "      version: Minilogue's Air Extend Remix"
    , "    - title: 'Martyr'"
    , "      version: Sound for the Universe Mix"
    , "    - title: 'Hole to Feed'"
    , "      version: Demo"
    , "    - title: 'Wrong'"
    , "      version: Extended Remix Edit"
    , "    - title: 'Wrong'"
    , "      version: Frankie's Bromantic Club Mix"
    , "    - title: 'Come Back'"
    , "      version: Studio Session 2 Mix"
    , "    - title: 'Wrong'"
    , "      version: Thin White Duke Remix"
    , "    - title: 'Come Back'"
    , "      version: Vinyl Mix"
    , "    - title: 'Wrong'"
    , "      version: D.I.M. vs. Boys Noize Remix"
    , "    - title: 'Corrupt'"
    , "      version: Efdemin Remix"
    , "    - title: 'Wrong'"
    , "      version: Peter Rauhofer Vocal Mix"
    , "    - title: 'In Chains'"
    , "      version: Minilogue's Earth Remix"
    , "    - title: 'Little Soul'"
    , "      version: Thomas Fehlman Ambient Mix"
    , "    - title: 'Wrong'"
    , "      version: Magda's Scallop Funk Remix"
    , "    - title: 'Jezebel'"
    , "      version: SixT\195\184es Remix"
    , "    - title: 'Wrong'"
    , "      version: Trentem\195\184ller Remix"
    , "    - title: 'Perfect'"
    , "      version: Drone Mix"
    , "    - title: 'Wrong'"
    , "      version: Caspa Remix"
    , "    - title: 'Oh Well'"
    , "      version: Black Light Odyssey Dub"
    , "    - title: 'Sun and the Moon and the Stars,The'"
    , "      version: Electronic Periodic's Microdrum Mix"
    , "    - title: 'Oh Well'"
    , "      version: Black Light Odyssey Remix"
    , "  -"
    , "    - title: Corrupt"
    , "      live_type: Session"
    , "      live_date: 2008-12-08"
    , "    - title: Little Soul"
    , "      live_type: Session"
    , "      live_date: 2008-12-08"
    , "    - title: Stories of Old"
    , "      live_type: Session"
    , "      live_date: 2008-12-08"
    , "    - title: Come Back"
    , "      live_type: Session"
    , "      live_date: 2008-12-08"
    , "" -- force a terminating newline
    ]

infosT ∷ ByteString
infosT =
  intercalate "\n" [ "---"
  , "artist: Depeche Mode"
  , "release: 2009-04-17"
  , "source: Sounds of the Universe"
  , "source_version: Deluxe Box Set"
  , "tracks:"
  , "  -"
  , "    - title: 'In Chains'"
  , "    - title: 'Hole to Feed'"
  , "  -"
  , "    - title: 'Wrong'"
  , "      version: Trentem\195\184ller Remix"
  , "    - title: 'Perfect'"
  , "      version: Drone Mix"
  , ""
  ]
